// Bundle inject/preload.src.js + the extension's content.css, rules.js, content.js into inject/preload.js.
import fs from "node:fs";
const ext = new URL("../youmood-extension/", import.meta.url);
const read = (n) => fs.readFileSync(new URL(n, ext), "utf8");
let src = fs.readFileSync(new URL("inject/preload.src.js", import.meta.url), "utf8");
src = src.replace('/*__CSS__*/""', JSON.stringify(read("content.css")))
         .replace("/*__RULES__*/", read("rules.js"))
         .replace("/*__CONTENT__*/", read("content.js"));
fs.writeFileSync(new URL("inject/preload.js", import.meta.url), "// GENERATED by build-inject.mjs — edit inject/preload.src.js or ../youmood-extension instead.\n" + src);
console.log("inject/preload.js bundled", src.length, "bytes");
